name: check
on:
  pull_request:
jobs:
  run-tests:
    strategy:
      matrix:
        module:
          - banking
          - expenses
          - invoices
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
          if [ "${{ matrix.module }}" == "banking" ]
          then
            exit 1
          else
            exit 0
          fi
