name: merge-gate-keeper
on:
  pull_request:
jobs:
  merge-gate-keeper:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.working-directory }}
          ref: ${{ inputs.git-checkout-ref }}
      - name: filter changed modules
        uses: actions/github-script@v6
        id: changed-modules
        with:
          script: |            
            const mergeGateKeeper = require("./.github/scripts/merge-gate-keeper.js")
            await mergeGateKeeper(core, github, context, "${{ github.head_ref }}")
